//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneticAlgo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneticAlgo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE 77534223
        ///AND 30997177
        ///ING 30679488
        ///ENT 17902107
        ///ION 17769261
        ///HER 15277018
        ///FOR 14686159
        ///THA 14222073
        ///NTH 14115952
        ///INT 13656197
        ///ERE 13287155
        ///TIO 13285065
        ///TER 12769843
        ///EST 11956466
        ///ERS 11823017
        ///ATI 11227573
        ///HAT 10900482
        ///ATE 10712298
        ///ALL 10501105
        ///ETH 10304110
        ///HES 10189449
        ///VER 10156140
        ///HIS 10051039
        ///OFT 9434246
        ///ITH 9142241
        ///FTH 9036651
        ///STH 9024058
        ///OTH 8869058
        ///RES 8835871
        ///ONT 8757161
        ///DTH 8745845
        ///ARE 8741156
        ///REA 8700830
        ///EAR 8697937
        ///WAS 8640940
        ///SIN 8629893
        ///STO 8556837
        ///TTH 8476119
        ///STA 8399345
        ///THI 8363593
        ///TIN 82180 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_trigrams {
            get {
                return ResourceManager.GetString("english_trigrams", resourceCulture);
            }
        }
    }
}
